"""primer

Revision ID: 5398834b7d50
Revises: 
Create Date: 2021-10-25 16:05:41.651484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5398834b7d50"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "primer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("seq", sa.String(), nullable=True),
        sa.Column("gc", sa.Float(), nullable=True),
        sa.Column("tm", sa.Float(), nullable=True),
        sa.Column("aliases", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("primer")
    # ### end Alembic commands ###
